[[redirects]]
  from = "/post/638930666016374784/your-music-not-mine-and-switching-to-tidal"
  to = "/music/2020/12/30/tidal.html"
  status = 301
  force = false

  [[redirects]]
  from = "https://suspicious-ritchie-a3d8aa.netlify.app/"
  to = "https://danielbower.com"
  status = 301
  force = true
